In [1]:
# pasted https://github.com/elastic/ember.git into git hub desktop
# that created clone under C:\Users\Moriah\Documents\GitHub\ember
# opened admin cmd
## python -m pip install --upgrade pip
## cd C:\Users\Moriah\Documents\GitHub\ember
## python -m pip install -r requirements.txt
## python setup.py install
## conda config --add channels conda-forge
## conda install --file requirements_conda.txt
## python setup.py install

# wont let me import ember on notebook so tried again
# added Anaconda 3 to system path, removed python from user path
# python -m pip install --upgrade --global http.sslVerify false
# that didnt work. changed sytem path to point to other version on anaconda3
# on admin cmd: python setup.py install # unsure if that worked
# on notebook: pip install ember # seemed like it worked
# import ember # error because missing lief
# pip install lief
 #import ember # no errors this time!

In [20]:
import numpy as np #data manipulation
import pandas as pd #data manipulation
import sklearn as sk #modeling & metrics
import seaborn as sns #visualizations
import scipy as stats #visualizations
from matplotlib import pyplot as plt #visualizations

#imputation, scaling, metrics
from sklearn import preprocessing
from sklearn.metrics import r2_score, classification_report, f1_score, accuracy_score, confusion_matrix
from sklearn.metrics import roc_curve, auc, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

#outlier classification
from sklearn.ensemble import IsolationForest

import xgboost as xgb #xgb model
import lightgbm as lgb #lgbm model
import re #fix error for lgbm
import hyperopt #hyperparameter tuning
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials, space_eval

import shap #shap plot

import pickle 
from collections import Counter

import re
import nltk
import spacy
import gensim
import string   
    
import warnings
warnings.filterwarnings('ignore')

import ember

In [10]:
# 0 benign, 1 malicious, -1 unlabled


In [8]:
ember.create_vectorized_features("C:/Users/Moriah/Documents/WorkRelated/HackTheMachine/Ember/")
ember.create_metadata("C:/Users/Moriah/Documents/WorkRelated/HackTheMachine/Ember/")

Vectorizing training set


100%|█████████████████████████████████████████████████████████████████████████| 800000/800000 [14:39<00:00, 910.04it/s]


Vectorizing test set


100%|█████████████████████████████████████████████████████████████████████████| 200000/200000 [03:32<00:00, 942.39it/s]


sha256 appeared  label  \
0       0abb4fda7d5b13801d63bee53e5e256be43e141faa077a...  2006-12      0   
1       c9cafff8a596ba8a80bafb4ba8ae6f2ef3329d95b85f15...  2007-01      0   
2       eac8ddb4970f8af985742973d6f0e06902d42a3684d791...  2007-02      0   
3       7f513818bcc276c531af2e641c597744da807e21cc1160...  2007-02      0   
4       ca65e1c387a4cc9e7d8a8ce12bf1bcf9f534c9032b9d95...  2007-02      0   
...                                                   ...      ...    ...   
999995  e033bc4967ce64bbb5cafdb234372099395185a6e0280c...  2018-12      1   
999996  c7d16736fd905f5fbe4530670b1fe787eb12ee86536380...  2018-12      1   
999997  0020077cb673729209d88b603bddf56b925b18e682892a...  2018-12      0   
999998  1b7e7c8febabf70d1c17fe3c7abf80f33003581c380f28...  2018-12      0   
999999  836063f2312b597632bca1f738e68e4d23f672d587a7fc...  2018-12      1   

          avclass subset  
0                  train  
1                  train  
2                  train  
3                  train  
4                  train  
...           ...    ...  
999995       zbot   test  
999996  flystudio   test  
999997              test  
999998              test  
999999     emotet   test  

[1000000 rows x 5 columns]

In [9]:
X_train, y_train, X_test, y_test = ember.read_vectorized_features("C:/Users/Moriah/Documents/WorkRelated/HackTheMachine/Ember/")
metadata_dataframe = ember.read_metadata("C:/Users/Moriah/Documents/WorkRelated/HackTheMachine/Ember/")

In [18]:
print(X_train.shape)

(800000, 2381)


In [26]:
print(X_train[:5,:256])

[[0.01467612 0.00422187 0.00392268 ... 0.00392365 0.00406099 0.00720765]
 [0.18452372 0.0313075  0.00569281 ... 0.00427506 0.00362468 0.05886342]
 [0.25173673 0.01420455 0.00684149 ... 0.00054932 0.00357888 0.07585005]
 [0.00896443 0.00405471 0.00392475 ... 0.00385578 0.00382844 0.00521506]
 [0.02040114 0.00521317 0.00451895 ... 0.00376059 0.00389233 0.00546798]]


In [15]:
lgbm_model = ember.train_model(r"C:/Users/Moriah/Documents/WorkRelated/HackTheMachine/Ember/")

[LightGBM] [Info] Number of positive: 300000, number of negative: 300000
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 14.455858 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 212057
[LightGBM] [Info] Number of data points in the train set: 600000, number of used features: 2333
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000


In [21]:
lgbm_model2 = lgb.Booster(model_file="C:/Users/Moriah/Documents/WorkRelated/HackTheMachine/Ember/ember_model_2018.txt")


In [22]:
putty_data = open("~/putty.exe", "rb").read()
print(ember.predict_sample(lgbm_model2, putty_data))

FileNotFoundError: [Errno 2] No such file or directory: '~/putty.exe'